# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://cdn.cocoapods.org/'

target 'MobillePaySDKSample' do
  pod 'Braintree'
	pod 'Braintree/Apple-Pay'
  pod 'Braintree/Card'
  pod 'Braintree/Venmo'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

